name: Compile Firmware and Check Size

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

          # Install standard libraries from the registry
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "ElegantOTA"

          # Install AiEsp32RotaryEncoder directly from GitHub
          arduino-cli lib install https://github.com/igorantolic/AiEsp32RotaryEncoder.git

          # Clone any custom libraries (e.g. Tapo API)
          mkdir -p ~/Arduino/libraries
          git clone https://github.com/Slaymish/tapo-esp32.git ~/Arduino/libraries/tapo-esp32

      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 light-controller/light-controller.ino --output-dir /tmp/build_output

      - name: Report Binary Size
        run: |
          SIZE_BYTES=$(arduino-cli compile --fqbn esp32:esp32:esp32 light-controller/light-controller.ino --show-properties sketch,size.total_bytes | cut -d '=' -f2 | tr -d '[:space:]')
          SIZE_KB=$(echo "scale=2; $SIZE_BYTES / 1024" | bc)
          echo "Binary size: $SIZE_BYTES bytes ($SIZE_KB KB)"
          # Uncomment to fail if size exceeds limit:
          # MAX_SIZE=1048576  # 1 MB
          # if [ "$SIZE_BYTES" -gt "$MAX_SIZE" ]; then
          #   echo "Error: Binary size ($SIZE_BYTES bytes) exceeds maximum allowed ($MAX_SIZE bytes)."
          #   exit 1
          # fi
